# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_hub', '0002_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='website',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='mygames',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
