# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_hub', '0003_auto_20180308_2021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('genre', models.CharField(max_length=200)),
                ('release_date', models.DateField(null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.CharField(max_length=200)),
                ('score', models.IntegerField(blank=True, default=1)),
                ('points', models.IntegerField(blank=True, default=0)),
                ('game_title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamer_hub.Game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamer_hub.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='platform',
            field=models.ManyToManyField(to='gamer_hub.Platform'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviews_downvoted',
            field=models.ManyToManyField(blank=True, related_name='users_downvoted', to='gamer_hub.Review'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reviews_upvoted',
            field=models.ManyToManyField(blank=True, related_name='users_upvoted', to='gamer_hub.Review'),
        ),
    ]
