# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 00:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_hub', '0005_auto_20180321_0350'),
        ('gamer_hub', '0004_auto_20180321_1645'),
    ]

    operations = [
    ]
