# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_hub', '0006_merge_20180325_0015'),
        ('gamer_hub', '0007_game_youtube_url'),
    ]

    operations = [
    ]
